name: pipeline CI
on: push

jobs:
  Test_job:
    runs-on: ubuntu-latest
    services: 
      postgres:
        image: postgres

        env:
          POSTGRES_USER: "Root_user"
          POSTGRES_PASSWORD: 12345
          POSTGRES_DB: projetintégrateur
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install backend dependencies
        run: |
          cd backend 
          npm install
          npm audit fix --force
      - name: Test
        run: |
          cd backend
          npm test -- --coverage
      - name: Install frontend dependencies & build
        if: success() || failure()
        run: |
          cd frontend
          npm install
          npm run build
      - name: run eslint
        run: |
          cd backend
          npx eslint --config eslint.config.mjs .
      - name: generate db
        run: |
          PGPASSWORD=12345 psql -h localhost -U Root_user -d projetintegrateur -f Base-de-données/createDatabase.sql
          PGPASSWORD=12345 psql -h localhost -U Root_user -d projetintegrateur -f Base-de-données/createTables.sql
          PGPASSWORD=12345 psql -h localhost -U Root_user -d projetintegrateur -f Base-de-données/creerUser.sql
          PGPASSWORD=12345 psql -h localhost -U Root_user -d projetintegrateur -f Base-de-données/grantUsersql
          PGPASSWORD=12345 psql -h localhost -U Root_user -d projetintegrateur -f Base-de-données/insertDonnees.sql
        env:
          POSTGRES_USER: "Root_user"
          POSTGRES_PASSWORD: 12345
          POSTGRES_DB: projetintégrateur
